pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
    }
    stages {
        stage('Terraform Apply') {
            steps {
                dir('lab2-task5') {
                    sh 'terraform init'
                    sh 'terraform apply -auto-approve'
                    // Save the IP to a file for Ansible
                    sh 'terraform output -raw public_ip > ec2_ip.txt'
                }
            }
        }
        stage('Ansible Install Nginx') {
            steps {
                dir('lab2-task5') {
                    script {
                        def ip = readFile('ec2_ip.txt').trim()
                        // Run ansible using the dynamic IP
                        sh "ansible-playbook -i ${ip}, -u ubuntu --private-key ${credentials('aws-ssh-key')} playbook.yml"
                    }
                }
            }
        }
    }
}